#define ULTRASONIC_ERROR 1

#define MASA_ERROR 2

#define ZGORNJI_THERMOCOUPLE_ERROR 4

#define SPODNJI_THERMOCOUPLE_ERROR 8

#define HANDSHAKE_TIMED_OUT 16

#define WRONG_HANDSHAKE 32

uint64_t *error_bit_mask;
